name: Build and Push Docker Image
run-name: Build and Push Docker Image for ${{ gitea.ref_name }} by @${{ gitea.actor }}
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    uses: twk95/actions/.gitea/workflows/build-and-deploy.yml@main
    with:
      service_name: opnsense-wol
      stacks_dir: /opt/stacks/opnsense-wol
    secrets: inherit

  deploy-demo:
    needs: build-and-deploy
    uses: twk95/actions/.gitea/workflows/build-and-deploy.yml@main
    with:
      service_name: opnsense-wol-demo
      stacks_dir: /opt/stacks/opnsense-wol
    secrets: inherit
