name: Build and Push Docker Image
run-name: Build and Push Docker Image for ${{ gitea.ref_name }} by @${{ gitea.actor }}
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    uses: hermes_bot/actions/.gitea/workflows/build-and-deploy.yml@main
    with:
      service_name: opnsense-wol
    secrets: inherit
