name: Publish to Docker Hub
run-name: Publish ${{ gitea.ref_name }} to Docker Hub by @${{ gitea.actor }}

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    uses: twk95/actions/.gitea/workflows/dockerhub-publish.yml@a84e4add8a3a7c5b0c10349ae33ac549c41bf4de
    with:
      image_name: ironicallyjesus/opnsense-wol-dash
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
